easy_admin:
  site_name: "YTS Subtitles"
  entities:
    Movies:
        class: App\Entity\Movie
        label: "Movies"
        list:
          # fields: [{property: 'id', label: false}, 'Title', {property: 'Year',label: 'Release Year',}, 'Runtime', {property: 'IMDM_Rating', label: 'IMDB Rating'}]
    Genre:
        class: App\Entity\Genre
        label: "Genre"
    Actor:
        class: App\Entity\Actor
        label: Actors
    Subtitle:
        class: App\Entity\Subtitle
        label: Subtitle
    Language:
        class: App\Entity\Language
        label: Language
      
